name: ArmA Clans
markdown: redcarpet
pygments: true

baseurl: /armaclans.de
thumbpath: /thumbs

collections:
- clandata

navleft:
  - title: Liste
    url: /index.html
  - title: Guide
    url: /guide.html
  - title: Neuer Eintrag
    url: /eintrag.html

navright:
  - title: About
    url: /about/